---
- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Run multiple commands on Cisco IOS nodes
      ios_command:
        commands: show ip int brief
      register: print_output
    - name: Debug registered var
      debug: var=print_output.stdout_lines
