---
- hosts: ips
  gather_facts: no
  conexión: network_cli

  
  tareas:
   - nombre: Mostrar interfaces 
     ios_command:
       
       comandos: 
         - mostrar ip int b
     registro: interfaz

   - depurar: var=interface.stdout_lines

