---

- name: Reach out to remote probes and troubleshoot routing
  hosts: all
  gather_facts: no
  vars:
    ansible_command_timeout: 120

  tasks:

    - name: Ping Destination
      routeros_command:
        commands:
          - "/ping count=10 destIP"
      register: pings
