---

- name: Running show commands on Cisco IOS
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios

  tasks:
    - name: Run a priviledged show command on Cisco IOS nodes
      ios_command:
        commands:
          - show ip int brief
      register: print_output

    - debug: var=print_output.stdout_lines
        
